name: Cypress Tests

# This workflow is documented as an example and will not run automatically.
# To enable it, uncomment the 'on' block below.
# on:
#   push:
#     branches:
#       - master
#       - main
#   pull_request:
#     branches:
#       - master
#       - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npx cypress run
